const express = require("express");
const Controller = require("../controllers/auth.controller");
const router = express.Router();
const Validate = require("../validators/index");
const SchemaValidateAuth = require("../validators/auth.validators");
const jwt = require("../services/jwt.services");
const  {defaultPermission } = require("../config/defaultModel");
const Permission = require("../services/permission.services");
router.post("/register", Validate.body(SchemaValidateAuth.register), Controller.register);
router.post("/registerStaff", jwt.verify, Permission.checkPermission(defaultPermission.Staff), Validate.body(SchemaValidateAuth.registerStaff), Controller.register);
router.post("/login", Validate.body(SchemaValidateAuth.login), Controller.login);
router.get("/verifyRegister/:token", jwt.verifyOTP, Controller.verified);
router.post("/requireResetPassword/", Validate.body(SchemaValidateAuth.requireResetPassword), Controller.requireResetPassword );
router.get("/verifyResetPassword/:token", jwt.verifyOTP, Controller.verifiedResetPassword);
router.post("/resetPassword", Validate.body(SchemaValidateAuth.resetPassword), Controller.resetPassword);
router.post("/changePassword", jwt.verify, Validate.body(SchemaValidateAuth.changePassword), Controller.changePassword);
module.exports = router;