const express = require("express");
const router = express.Router();
const Controller = require("../controllers/category.controller");
const Validate = require("../validators/index");
const SchemaValidateCategory = require("../validators/category.validators");
router.get("/getAllCategories", Controller.getAllCategories);
router.post("/createCategory",Validate.body(SchemaValidateCategory.create), Controller.createCategory);
router.put("/editCategory", Validate.body(SchemaValidateCategory.edit), Controller.editCategory);
router.delete("/deleteCategory", Validate.body(SchemaValidateCategory.delete), Controller.deleteCategory);
router.get("/getAllSubCategories", Controller.getAllSubCategories);
router.post("/createSubCategory", Validate.body(SchemaValidateCategory.createSubCategory), Controller.createSubCategory);
router.put("/editSubCategory", Validate.body(SchemaValidateCategory.editSubCategory), Controller.editSubCategory);
router.delete("/deleteSubCategory", Validate.body(SchemaValidateCategory.delete), Controller.deleteSubCategory);
module.exports = router;