const express = require("express");
const productRoute = require("../routes/product.route");
const authRoute = require("../routes/auth.route");
const categoryRoute = require("../routes/category.route");
const trademarkRoute = require("../routes/trademark.route");
const positionRoute = require("../routes/position.route");
const userRoute = require("../routes/user.route");
const cartRoute = require("../routes/cart.route");
const billRoute = require("../routes/bill.route");
const router = express.Router();
router.use("/product", productRoute);
router.use("/category", categoryRoute);
router.use("/trademark", trademarkRoute);
router.use("/position", positionRoute);
router.use("/user", userRoute);
router.use("/cart", cartRoute);
router.use("/bill", billRoute);
router.use("/", authRoute);
module.exports = router;